version: '3.8'
services:
  front-nginx: # 前端node容器(运行nginx中的前端项目)
    restart: always # 重启策略: 容器退出时总是重启容器
    build:
      context: ./ # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: docker/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - '80:8101' # 映射端口
    # networks:
    #   - frontend-network-web # 设置网卡
# networks:
#   frontend-network-web:
#     driver: bridge
